### ISSUE TITLE
Watchface canvas are not updated, analog watchfaces stand still

### ISSUE THREAD

**Issue by eLtMosen** [AsteroidOS/asteroid-launcher#30]
I am currently making a custom watchfaces that i would like to contribute to unofficial repo but when testing on dory and lenok with 20180115 nightly the canvases seem to not get updated.
Only the text display shows the correct output.

Testing all other watchfaces that use canvas to display analog arms also "stand still" and always remain in the state shown when selected in settings watchface selector.

As i am just getting started with qml exercise it would be really helpfull and reassuring to have correct "feedback" when testing on device.

**Comment by jgibbon** [comment]
Hi Mosen, nice to see you here!
When I did my own little watchface this week, I had to put a little update section [like this one](https://github.com/AsteroidOS/asteroid-launcher/blob/master/watchfaces/003-alternative-digital.qml#L86) in and updates worked.
Haven't really tested the built-in ones, though: A "knight rider look" was the first thing I needed. :)

kind regards,
velox

**Comment by FlorentRevest** [comment]
Unfortunately, watchfaces grew in complexity quite a bit.
They used to use simple property bindings on Text items but we had to switch to Canvas so that they can be properly rendered on all watches. This also meant that we had to draw watchfaces with onPaint and manually repaint each Canvas when needed. This is done with the ugly block of code pointed by jgibbon.
Make sure you check the results of "journalctl -u user@1000 --no-pager" ran as root to see if a qml error occurs when using a faulty watchface and if it happens with one of the official one, report with logs.
Also, thanks for having considered a contribution to [the unofficial-watchfaces repository](https://github.com/AsteroidOS/unofficial-watchfaces) @eLtMosen . I'd love to see your work there. 
@jgibbon would you be interested in sharing your watchface there too?

**Comment by jgibbon** [comment]
@FlorentRevest of course, I'll look into that – I just have to re-paint (or make an svg of?) the background image I used to not infringe on someones rights when time (hah.) allows.

**Comment by eLtMosen** [comment]
Hi velox! 
Many thanks for the code hint. I got it working after some mild fiddeling.
@FlorentRevest will do in the next days, now that i know velox is watching i need to polish some more chrchrchr
Won't mind to close the issue as the proposed solution is in the same skill level than the problem ;)
