### ISSUE TITLE
[Feature Request] Velocity based scrolling through application list

### ISSUE THREAD

**Issue by Doomsdayrs** [AsteroidOS/asteroid-launcher#53]
Currently, If one wants to go from the start of the application list to the end, one needs to slowly scroll through all the applications, no matter how fast they swipe.

Taking velocity of the swipe into account can help improve the snappiness of the entire UI. This also effects other applications, such as settings where scrolling feels just as sluggish.

**Comment by MagneFire** [comment]
The application list uses a qml ListView to display the app icons. We could try and adjust the `maximumFlickVelocity` (https://doc.qt.io/qt-5/qml-qtquick-flickable.html#maximumFlickVelocity-prop) to see if that changes the behaviour. As it seems that it is actually using velocity based scrolling (slow vs faster is definitely possible). So it might just be limited on the watch you are using.

This is different for the settings app. To me it feels like this app feels sluggish due to it being a bit more complex in comparison to other AsteroidOS apps, we might want to play around with other options here. `cacheBuffer` is something that pops up often as a solution to decrease sluggishness.

**Comment by eLtMosen** [comment]
> Currently, If one wants to go from the start of the application list to the end, one needs to slowly scroll through all the applications, no matter how fast they swipe.

The scrolling actually is swipe velocity dependend. The stock applauncher just behaves like that (long scroll distance at max scroll velocity) since the app icons are very big and thus the list very long. The new launcher styles are much shorter lists and your wish to reach outer most items thus mitigated.
Setting the scroll velocity even faster would bring problems in precision.

> Taking velocity of the swipe into account can help improve the snappiness of the entire UI. This also effects other applications, such as settings where scrolling feels just as sluggish.

This is a different problem referenced here:
The settings mainpage list is indeed sluggish to scroll and worked on.
https://github.com/AsteroidOS/asteroid-settings/issues/37
