### ISSUE TITLE
WallClock does not update for daylight saving time

### ISSUE THREAD

**Issue by TheLastProject** [AsteroidOS/asteroid-launcher#6]
I'm not sure where to best place the issue, and I suppose this problem fixes itself when syncing with your phone, but it would still be nice if AsteroidOS understood daylight saving time, letting you enable/disable it in settings, for usage without a phone.

**Comment by FlorentRevest** [comment]
It's most likely just a matter of configuring "timed" correctly but this is not high on my priority list. I'll let this bug open for now.

**Comment by FlorentRevest** [comment]
I just checked timed's sourcecode regarding daylight saving time and it's only used when enabling network time synchronization, it can't be used standalone.
This issue is tough to fix and could be handled by the asteroid-btsyncd's Time BLE profile so I'll close it for now and re-open in case it becomes really problematic later.
